[package]
name = "plugin-example"
version = "0.1.0"
edition = "2021"

[package.metadata.component]
target = { path = "../plugin-host/simple-component.wit" }

[lib]
crate-type = [ "cdylib" ]

[dependencies]
wit-bindgen = "0.8.0"
